"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const bodyParser = require("body-parser");
const socketIO = require("socket.io");
const path = require("path");
const cors = require("cors");
const http = require("http");
const lobby_1 = require("./gameServer/lobby");
const router_1 = require("./router");
require("./db/index");
const port = process.env.PORT || 8080;
const app = express();
const server = http.createServer(app);
const io = socketIO(server);
lobby_1.default(io);
app.use(bodyParser.json());
app.use(cors());
app.use('/api', router_1.default);
app.use(express.static(path.join(__dirname, '..', 'game-client', 'dist')));
server.listen(port, () => console.log("listening on port " + port));
