export const highGroundDeck: string[] = [
    "Kidney Jab",
    "Groin Stomp",
    "Precise Kick",
    "'Ol 1, 2",
    "Kip Up",
    "Bolas",
    "Drop Caltrops",
    "Defensive Roll",
    "Wind Up",
    "Knife Throw",
    "Throat Jab",
    "Human Ladder",
    "Spring Trap",
    "Going For The High Ground",
    "Rip From Socket",
    "Backflip",
    "Throw Person",
]