export const gladiatorDeck: string[] = [
    "Throw Net",
    "Ready Trident",
    "Spinning Slash",
    "Tendon Slash",
    "Skewer",
    "Flying Slash",
    "Grand Setup",
    "Feign Strength",
    "Tie The Noose",
    "Feint",
    "Death From Above",
    "Cheap Trick",
    "Pull By The Neck",
    "Goad",
    "Find The Joint",
    "Desperate Swing",
    "Charging Flourish",
    "Bloody Flourish"
]