export const grappleDeck: string[] = [
    "Flying Kick",
    "Charge",
    "Lunge",
    "Body Slam",
    "Defensive Crawl",
    "Sweep The Legs",
    "Hit The Floor",
    "Grounded",
    "Smash Kneecap",
    "Neck Break",
    "Leg Grab",
    "Joint Lock",
    "To The Ground",
    "Circle Opponent",
    "Opportunist",
    "Study Balance",
    "Going For The Pin",
    "Ground Grab",
    "Throw Rock",
    "Surefooted Smash"]