"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var MechanicEnum;
(function (MechanicEnum) {
    MechanicEnum["TELEGRAPH"] = "Telegraph";
    MechanicEnum["FOCUS"] = "Focus";
    MechanicEnum["PREDICT"] = "Predict";
    MechanicEnum["BLOCK"] = "Block";
    MechanicEnum["LOCK"] = "Lock";
    MechanicEnum["REFLEX"] = "Reflex";
    MechanicEnum["BUFF"] = "Buff";
    MechanicEnum["CRIPPLE"] = "Cripple";
    MechanicEnum["PICK_ONE"] = "Pick One";
    MechanicEnum["FORCEFUL"] = "Forceful";
})(MechanicEnum = exports.MechanicEnum || (exports.MechanicEnum = {}));
var AxisEnum;
(function (AxisEnum) {
    AxisEnum["DAMAGE"] = "Damage";
    AxisEnum["PRONE"] = "Prone";
    AxisEnum["STANDING"] = "Standing";
    AxisEnum["MOVING"] = "Moving";
    AxisEnum["STILL"] = "Still";
    AxisEnum["GRAPPLED"] = "Grappled";
    AxisEnum["NOT_GRAPPLED"] = "Not Grappled";
    AxisEnum["CLOSE"] = "Close";
    AxisEnum["NOT_CLOSE"] = "Not Close";
    AxisEnum["FAR"] = "Far";
    AxisEnum["NOT_FAR"] = "Not Far";
    AxisEnum["BALANCED"] = "Balanced";
    AxisEnum["UNBALANCED"] = "Unbalanced";
    AxisEnum["ANTICIPATING"] = "Anticipating";
    AxisEnum["CLOSER"] = "Closer";
    AxisEnum["FURTHER"] = "Further";
    AxisEnum["BLOODIED"] = "Bloodied";
    AxisEnum["MOTION"] = "Motion";
    AxisEnum["DISTANCE"] = "Distance";
    AxisEnum["POISE"] = "Poise";
    AxisEnum["LOSE_POISE"] = "Lose Poise";
    AxisEnum["STANCE"] = "Stance";
})(AxisEnum = exports.AxisEnum || (exports.AxisEnum = {}));
var PlayerEnum;
(function (PlayerEnum) {
    PlayerEnum[PlayerEnum["PLAYER"] = 0] = "PLAYER";
    PlayerEnum[PlayerEnum["OPPONENT"] = 1] = "OPPONENT";
    PlayerEnum[PlayerEnum["BOTH"] = 2] = "BOTH";
})(PlayerEnum = exports.PlayerEnum || (exports.PlayerEnum = {}));
